; Configuration file for Duet WiFi (firmware version 3.3)
; Generated by RepRapFirmware Configuration Tool v3.3.5
; Last modified: Mon Nov 15 2021 16:57:49 GMT-0500 (Eastern Standard Time)

;==========================================
; Network Configuration
;==========================================
M551 P"benderisgreat"                           ; Set network password
M669 K0                                         ; Set kinematics type
G4 S2                                           ; Wait for expansion boards to start

;==========================================
; General Preferences
;==========================================
G90                                             ; Send absolute coordinates
M83                                             ; Relative extruder moves
;M550 P"Sensing Technology Lab MMP"             ; Set printer name (commented out)

;==========================================
; Drive Configuration
;==========================================
; Motor Direction Configuration
M569 P0.0 S0                                    ; Physical drive 0 goes backwards
M569 P0.1 S0                                    ; Physical drive 1 goes backwards
M569 P0.2 S0                                    ; Physical drive 2 goes forwards
M569 P0.3 S0                                    ; Physical drive 3 goes backwards
M569 P0.4 S1                                    ; Physical drive 4 goes backwards
M569 P0.5 S1                                    ; Physical drive 5 goes backwards
M569 P1.0 S1                                    ; Physical drive 6 goes backwards
M569 P1.1 S0                                    ; Physical drive 7 goes backwards
M569 P1.2 S0                                    ; Physical drive 8 goes backwards
M569 P2.0 S0                                    ; Physical Drive 9 goes backwards
M569 P2.1 S0                                    ; Physical Drive 10 goes backwards



; Drive Mapping
M584 X0.0 Y1.2 Z0.4:1.0 E1.1:0.5 U0.1 V0.3      ; Set drive mapping (Z left:right)
M584 A0.2 B2.0 C2.1 S0 R0                                 ; Set A axis mapping A = rotary tool, B  =  Feeder, C = PnP Rot

; Microstepping and Steps Configuration
M350 X32 Y32 Z16 E32:16 U16 V32 A32 B32 C32 I1         ; Configure microstepping with interpolation
M92 X160.00 Y160.00 Z400.00 E260:30704 U80.00 V160.00 A71.111111 B71.1111111 C17.77777   ; Set steps per mm/degree

; Speed and Acceleration Settings
M566 X600.00 Y600.00 Z300.00 E300.00:600 U600 V600 A900 B900 C900 ; Maximum instantaneous speed changes (mm/min)
M203 X12000.00 Y12000.00 Z2400 E1500:35 U12000 V12000 A12000  B12000 C12000 ; Maximum speeds (mm/min)
M201 X500.00 Y500.00 Z350.00 E200.00:500.00 U600.0 V600 A9000 B9000 C9000 ; Accelerations (mm/s^2)
M906 X1600 Y1600 Z1200 E1600:800 U1600 V1600 A400 B400 C400 I30  ; Motor currents (mA) and idle factor
M84 S30                                         ; Set idle timeout

;==========================================
; Axis Limits
;==========================================
M208 X-30 Y0 Z0 U0 V-73 S1 A-3600              ; Set axis minima
M208 X326.55 Y378.8 Z200 U370 V266.55 S0 A3600 ; Set axis maxima

;==========================================
; Endstops Configuration
;==========================================
M574 X2 S1 P"1.IO4.in"                         ; X axis endstop
M574 Y1 S1 P"1.IO1.in"                         ; Y axis endstop
M574 Z1 S1 P"0.IO3.in+1.IO5.in"                ; Z axis endstops (left+right)
M574 V2 S1 P"0.IO1.in"                         ; V axis high end endstop
M574 U1 S1 P"0.IO8.in"                         ; U axis high end microswitch

;==========================================
; Z-Probe Configuration
;==========================================
; Tool 0 Probe (XYZ)
M558 K0 P9 C"io5.in" H3 F60 T10000             ; Configure BLTouch probe
G31 K0 P500 X-43.5 Y-102.8 U0.0 Z17.420        ; Set Z probe trigger value and offset
M950 S0 C"io5.out"                             ; Create servo #0 for BLtouch

; Tool 2 Probe (VYZ)
M558 K1 P9 C"0.io7.in" H4 F60 T6000            ; Configure BLTouch probe
G31 K1 P500 X0.0 Y-101.8 U-160 Z3.290          ; Set Z probe trigger value and offset
M950 S1 C"0.io7.out"                           ; Create servo #1 for BLtouch

M557 X10:210 Y10:210 P9                        ; Define mesh grid

;==========================================
; Heater Configuration
;==========================================
; Bed Heater
M308 S0 P"temp0" Y"thermistor" T100000 B4138   ; Configure bed thermistor
M950 H0 C"0.out1" T0                           ; Create bed heater output
M307 H0 R0.345 K0.235:0.000 D3.29 E1.35 S1.00 B0  ; Bed heater parameters
M140 H0                                        ; Map heated bed to heater 0
M143 H0 S150                                   ; Set temperature limit to 150C

; Tool 0 Nozzle Heater
M308 S2 P"temp2" Y"thermistor" T100000 B4138   ; Configure nozzle thermistor
M950 H2 C"0.out3" T2                           ; Create nozzle heater output
M307 H2 R4.782 K0.914:0.000 D3.71 E1.35 S1.00 B0 V23.7  ; Nozzle heater parameters
M143 H2 S450                                   ; Set temperature limit to 450C

;==========================================
; Fan Configuration
;==========================================
M950 F0 C"out9" Q500                           ; Create fan 0
M106 P0 S0 H-1                                 ; Set fan 0 value
M950 F1 C"1.out2"                              ; Vacuum pump output
M950 F2 C"1.out1"                              ; Pneumatic solenoid output
M950 F3 C"1.IO0.out"                           ; LED Ring light output 1
M950 F4 C"1.IO3.out"                           ; LED Ring light output 2
M106 P1 S0 H-1                                 ; Initialize fan 1
M106 P2 S0 H-1                                 ; Initialize fan 2
M106 P3 S0 H-1                                 ; Initialize fan 3 - arduino controlled LED RING
M106 P4 S0 H-1                                 ; Initialize fan 4 - arduino controlled LED RING

;==========================================
; Tool Configuration
;==========================================
; Tool 0 (FFF head right)
M563 P0 D0 H2 F0                               ; Define tool 0
G10 P0 S0                                      ; Set initial temperatures
G10 P0 X0.015 Y-102.190 Z-8.550 U0.000 V0.000 A0.000  ; Set tool 0 offsets

; Tool 1 (inkhead left)
M563 P1 D1 X3                                  ; Define tool 1
G10 P1 X0.000 Y-71.175 Z-10.400 U-164.595 V0.000 A0.000  ; Set tool 1 offsets

; Tool 2 (PnP Head, Center)
M563 P2 X4                                     ; Define tool 2
G10 P2 Z-14.35 V-10.55 Y-74.3                  ; Set tool 2 offsets
G92 A0 B0 C0                                        ; Set V axis to homed at zero

; Tool 3 (PnP Camera Head)
M563 P3 X4                                     ; Define tool 3
G10 P3 V-3.82 Y-114.660 Z26
;==========================================
; Final Configuration
;==========================================
G29 S2                                         ; Clear bed compensation